### PR TITLE
Update wording, formatting, case and usage

### PR DESCRIPTION
**Pull request by peterdell**
Hello Tebe,
Please check my proposals for the updated English documentation. I've applied the same rules & wording as for the Mad-Assembly documentation. You can find details in the commit comments.
Kind regards, Peter/JAC!

### CODE REVIEW

**Comment by zbyti** [comment]
nice work, thx!

**Comment by peterdell** [comment]
Hello zbyti,
You closed the request without merging it. I think you wanted to merge, right?
Regards, Peter.

**Comment by zbyti** [comment]
@peterdell sorry ;)

**Comment by peterdell** [comment]
Ok THAT was fast 👍

**Pull request merged**
